
import { type MenuItem } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  return PlaceHolderImages.find(img => img.id === id)?.imageUrl || `https://picsum.photos/seed/${id}/600/400`;
};

export const initialMenuItems: Omit<MenuItem, "id" | "votes">[] = [
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'breakfast',
    day: 'monday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'breakfast',
    day: 'monday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'breakfast',
    day: 'tuesday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'breakfast',
    day: 'tuesday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Ven Pongal',
    description: 'A savory and comforting South Indian breakfast dish made from rice and yellow moong dal, cooked to a creamy consistency and tempered with spices.',
    category: 'breakfast',
    day: 'wednesday',
    ingredients: ['Raw Rice', 'Moong Dal', 'Ghee', 'Black Peppercorns', 'Cumin Seeds', 'Cashew Nuts', 'Ginger', 'Curry Leaves'],
    instructions: '1. Dry roast moong dal until aromatic. Cook rice and dal together with water until soft and mushy.\n2. In a pan, heat ghee and temper with peppercorns, cumin seeds, ginger, and curry leaves.\n3. Fry cashews until golden brown.\n4. Add the tempering and fried cashews to the cooked rice and dal mixture. Mix well and serve hot.',
    imageUrl: getImage('ven-pongal'),
    imageHint: 'pongal dish',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '450 kcal', protein: '15g', carbs: '60g', fat: '18g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'breakfast',
    day: 'wednesday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'breakfast',
    day: 'wednesday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Poori Masala',
    description: 'Fluffy, deep-fried bread (poori) served with a savory and mildly spiced potato curry (masala). A popular and beloved breakfast combination.',
    category: 'breakfast',
    day: 'thursday',
    ingredients: ['Whole Wheat Flour', 'Potatoes', 'Onions', 'Green Chilies', 'Turmeric Powder', 'Mustard Seeds', 'Urad Dal'],
    instructions: '1. Prepare a dough for poori and roll out small discs. Deep fry until they puff up and turn golden brown.\n2. For the masala, boil and mash potatoes. Sauté onions, chilies, and spices. Add potatoes and cook until combined.\n3. Serve hot pooris with the potato masala.',
    imageUrl: getImage('poori-masala'),
    imageHint: 'poori masala',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '450 kcal', protein: '10g', carbs: '70g', fat: '15g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'breakfast',
    day: 'thursday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'breakfast',
    day: 'thursday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Ghee Roast Dosa',
    description: 'A super crispy, cone-shaped dosa cooked with a generous amount of ghee until it turns a deep golden-brown. Famous for its rich flavor and crisp texture.',
    category: 'breakfast',
    day: 'friday',
    ingredients: ['Dosa Batter', 'Ghee', 'Idli Podi (optional)'],
    instructions: '1. Heat a tawa until very hot. Spread batter thinly.\n2. Drizzle generously with melted ghee all over the dosa.\n3. Cook on medium-low flame until the underside is a deep golden brown and the dosa is very crisp.\n4. Roll it into a cone or a cylinder. Serve immediately with sambar and a variety of chutneys.',
    imageUrl: getImage('ghee-roast'),
    imageHint: 'ghee roast',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '420 kcal', protein: '7g', carbs: '55g', fat: '20g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'breakfast',
    day: 'friday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'breakfast',
    day: 'friday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'breakfast',
    day: 'saturday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'breakfast',
    day: 'saturday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'breakfast',
    day: 'sunday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'breakfast',
    day: 'sunday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Bisi Bele Bath',
    description: 'A traditional Karnataka dish, this is a flavorful and aromatic rice, lentil, and vegetable medley, cooked with a special spice blend (bisi bele bath powder).',
    category: 'lunch',
    day: 'monday',
    ingredients: ['Rice', 'Toor Dal', 'Mixed Vegetables', 'Bisi Bele Bath Powder', 'Tamarind', 'Ghee', 'Mustard Seeds', 'Peanuts'],
    instructions: '1. Cook rice, dal, and vegetables together until soft.\n2. Prepare a tempering with ghee, mustard seeds, peanuts, and curry leaves.\n3. Mix the cooked rice-dal mixture with tamarind extract and bisi bele bath powder.\n4. Add the tempering and mix everything well. Serve hot with a side of chips or boondi.',
    imageUrl: getImage('bisi-bele-bath'),
    imageHint: 'rice dish',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '550 kcal', protein: '20g', carbs: '80g', fat: '15g' },
    submitterId: 'management',
  },
  {
    title: 'Lemon Rice (Chitranna)',
    description: 'A tangy, flavorful, and light rice dish from South India. Cooked rice is tossed with a tempering of spices and a generous amount of lemon juice.',
    category: 'lunch',
    day: 'tuesday',
    ingredients: ['Cooked Rice', 'Lemon Juice', 'Mustard Seeds', 'Urad Dal', 'Chana Dal', 'Peanuts', 'Turmeric Powder', 'Green Chilies', 'Curry Leaves'],
    instructions: '1. Fluff up the cooked rice and let it cool slightly.\n2. Heat oil in a pan and add mustard seeds, urad dal, chana dal, and peanuts. Sauté until golden.\n3. Add green chilies, curry leaves, and turmeric powder. Sauté for a minute.\n4. Pour this tempering over the rice. Add salt and fresh lemon juice.\n5. Mix gently until everything is well combined. Garnish with coriander.',
    imageUrl: getImage('lemon-rice'),
    imageHint: 'lemon rice',
    dietaryInfo: 'vegan',
    nutrition: { calories: '400 kcal', protein: '9g', carbs: '75g', fat: '8g' },
    submitterId: 'management',
  },
  {
    title: 'Sambar Rice',
    description: 'A wholesome and flavorful one-pot meal where rice and lentils are cooked together with a variety of vegetables and aromatic sambar powder.',
    category: 'lunch',
    day: 'thursday',
    ingredients: ['Rice', 'Toor Dal', 'Mixed Vegetables', 'Sambar Powder', 'Tamarind', 'Ghee', 'Mustard Seeds'],
    instructions: '1. Pressure cook rice, dal, and vegetables together with sambar powder and tamarind extract.\n2. Mash the mixture slightly to get a semi-thick consistency.\n3. Prepare a tempering with ghee and mustard seeds, and pour it over the sambar rice.\n4. Mix well and serve hot with a side of appalam (papad).',
    imageUrl: getImage('sambar-rice'),
    imageHint: 'sambar rice',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '480 kcal', protein: '18g', carbs: '90g', fat: '8g' },
    submitterId: 'management',
  },
  {
    title: 'Onion Pakoda',
    description: 'Crispy and crunchy fritters made with thinly sliced onions mixed in a spiced gram flour batter and deep-fried until golden brown. A perfect evening snack.',
    category: 'snack',
    day: 'friday',
    ingredients: ['Onions', 'Gram Flour (Besan)', 'Rice Flour', 'Red Chili Powder', 'Asafoetida', 'Curry Leaves', 'Oil for frying'],
    instructions: '1. Thinly slice onions. Mix with gram flour, rice flour, chili powder, salt, and other spices. Add very little water to form a thick, coarse batter.\n2. Heat oil in a deep pan.\n3. Drop small portions of the onion mixture into the hot oil and fry until golden brown and crispy.\n4. Drain excess oil and serve hot with chutney or ketchup.',
    imageUrl: getImage('onion-pakoda'),
    imageHint: 'onion pakoda',
    dietaryInfo: 'vegan',
    nutrition: { calories: '300 kcal', protein: '8g', carbs: '35g', fat: '15g' },
    submitterId: 'management',
  },
  {
    title: 'Chapathi with Kurma',
    description: 'Soft, unleavened flatbreads (chapathi) served with a rich and creamy mixed vegetable curry (kurma) made with a coconut-based gravy.',
    category: 'dinner',
    day: 'monday',
    ingredients: ['Whole Wheat Flour', 'Mixed Vegetables', 'Coconut', 'Onion', 'Tomato', 'Ginger-Garlic Paste', 'Spices'],
    instructions: '1. Prepare soft dough and roll out thin chapathis. Cook on a hot tawa until puffed up.\n2. Prepare kurma by grinding a coconut-spice paste. Sauté onions and tomatoes, add vegetables and the ground paste. Cook until vegetables are tender and gravy is thick.\n3. Serve hot chapathis with vegetable kurma.',
    imageUrl: getImage('chapathi-kurma'),
    imageHint: 'chapathi kurma',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '500 kcal', protein: '15g', carbs: '80g', fat: '15g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'dinner',
    day: 'monday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'dinner',
    day: 'monday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'dinner',
    day: 'tuesday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'dinner',
    day: 'tuesday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Chapathi with Kurma',
    description: 'Soft, unleavened flatbreads (chapathi) served with a rich and creamy mixed vegetable curry (kurma) made with a coconut-based gravy.',
    category: 'dinner',
    day: 'wednesday',
    ingredients: ['Whole Wheat Flour', 'Mixed Vegetables', 'Coconut', 'Onion', 'Tomato', 'Ginger-Garlic Paste', 'Spices'],
    instructions: '1. Prepare soft dough and roll out thin chapathis. Cook on a hot tawa until puffed up.\n2. Prepare kurma by grinding a coconut-spice paste. Sauté onions and tomatoes, add vegetables and the ground paste. Cook until vegetables are tender and gravy is thick.\n3. Serve hot chapathis with vegetable kurma.',
    imageUrl: getImage('chapathi-kurma'),
    imageHint: 'chapathi kurma',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '500 kcal', protein: '15g', carbs: '80g', fat: '15g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'dinner',
    day: 'wednesday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'dinner',
    day: 'wednesday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'dinner',
    day: 'thursday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'dinner',
    day: 'thursday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'dinner',
    day: 'friday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'dinner',
    day: 'friday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'dinner',
    day: 'saturday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'dinner',
    day: 'saturday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  },
  {
    title: 'Idli with Sambar & Chutney',
    description: 'Soft, fluffy steamed rice cakes made from a fermented rice and lentil batter. Served with a flavorful lentil-based vegetable stew (sambar) and coconut chutney.',
    category: 'dinner',
    day: 'sunday',
    ingredients: ['Idli Batter', 'Toor Dal (Pigeon Peas)', 'Mixed Vegetables', 'Sambar Masala', 'Tamarind', 'Mustard Seeds', 'Coconut', 'Green Chilies'],
    instructions: '1. Pour idli batter into greased idli molds.\n2. Steam for 10-12 minutes until cooked through.\n3. Prepare sambar by cooking lentils and vegetables with spices.\n4. Prepare chutney by grinding coconut, green chilies, and other ingredients.\n5. Serve hot idlis with a generous portion of sambar and chutney.',
    imageUrl: getImage('idli-sambar'),
    imageHint: 'idli sambar',
    dietaryInfo: 'vegan',
    nutrition: { calories: '250 kcal', protein: '10g', carbs: '45g', fat: '5g' },
    submitterId: 'management',
  },
  {
    title: 'Masala Dosa',
    description: 'A crispy and savory crepe made from fermented rice and lentil batter, filled with a spiced potato mash. A South Indian classic.',
    category: 'dinner',
    day: 'sunday',
    ingredients: ['Dosa Batter', 'Potatoes', 'Onions', 'Turmeric Powder', 'Mustard Seeds', 'Curry Leaves', 'Ghee/Oil'],
    instructions: '1. Prepare the spiced potato filling.\n2. Heat a non-stick tawa or griddle.\n3. Pour a ladleful of dosa batter and spread it in a circular motion to form a thin crepe.\n4. Drizzle with oil or ghee and cook until golden and crisp.\n5. Place the potato filling in the center, fold the dosa, and serve hot with sambar and chutney.',
    imageUrl: getImage('masala-dosa'),
    imageHint: 'masala dosa',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '380 kcal', protein: '8g', carbs: '65g', fat: '10g' },
    submitterId: 'management',
  }
];
