import { type MenuItem } from './types';

export const initialMenuItems: MenuItem[] = [
  {
    id: '1',
    title: 'Spaghetti Aglio e Olio',
    description: 'A traditional Italian pasta dish from Naples, simple yet bursting with flavor. Made by lightly sautéing garlic in olive oil.',
    ingredients: ['200g Spaghetti', '4 cloves Garlic', '50ml Olive Oil', '1 tsp Red Pepper Flakes', 'Salt', 'Fresh Parsley'],
    instructions: '1. Cook spaghetti according to package directions.\n2. While pasta is cooking, heat olive oil in a large skillet over medium heat.\n3. Add sliced garlic and cook until golden brown, about 2-3 minutes.\n4. Add red pepper flakes and cook for another 30 seconds.\n5. Drain pasta, reserving a cup of pasta water.\n6. Toss spaghetti with the garlic oil, adding pasta water as needed to create a sauce. Garnish with fresh parsley.',
    imageUrl: 'https://picsum.photos/seed/101/600/400',
    imageHint: 'pasta bowl',
    dietaryInfo: 'vegan',
    nutrition: { calories: '550 kcal', protein: '12g', carbs: '70g', fat: '25g' },
    votes: 28,
  },
  {
    id: '2',
    title: 'Mediterranean Quinoa Salad',
    description: 'A refreshing and healthy salad, perfect for a light lunch. Packed with fresh vegetables, herbs, and a zesty lemon dressing.',
    ingredients: ['1 cup Quinoa, rinsed', '1 Cucumber, diced', '1 cup Cherry Tomatoes, halved', '1/2 Red Onion, thinly sliced', '1/4 cup Kalamata Olives', '1/4 cup Feta Cheese, crumbled', 'Lemon Juice', 'Olive Oil'],
    instructions: '1. Cook quinoa according to package directions and let it cool completely.\n2. In a large bowl, combine the cooked quinoa, cucumber, cherry tomatoes, red onion, and olives.\n3. In a small bowl, whisk together lemon juice and olive oil for the dressing.\n4. Pour dressing over the salad and toss to combine.\n5. Gently stir in the feta cheese just before serving.',
    imageUrl: 'https://picsum.photos/seed/102/600/400',
    imageHint: 'salad bowl',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '450 kcal', protein: '15g', carbs: '50g', fat: '22g' },
    votes: 42,
  },
  {
    id: '3',
    title: 'Classic Margherita Pizza',
    description: 'The quintessential Neapolitan pizza, topped with San Marzano tomatoes, fresh mozzarella, fresh basil, salt, and extra-virgin olive oil.',
    ingredients: ['1 Pizza Dough ball', '1/2 cup San Marzano Tomato Sauce', '150g Fresh Mozzarella Cheese, sliced', 'Handful of Fresh Basil leaves', 'Extra Virgin Olive Oil', 'Salt'],
    instructions: '1. Preheat your oven and pizza stone to 250°C (475°F).\n2. Stretch the pizza dough into a 12-inch circle on a lightly floured surface.\n3. Spread a thin layer of tomato sauce over the dough, leaving a small border.\n4. Arrange mozzarella slices evenly on top.\n5. Bake for 10-12 minutes, or until the crust is golden and cheese is bubbly.\n6. Top with fresh basil leaves, a drizzle of olive oil, and a pinch of salt.',
    imageUrl: 'https://picsum.photos/seed/103/600/400',
    imageHint: 'pizza slice',
    dietaryInfo: 'vegetarian',
    nutrition: { calories: '750 kcal', protein: '30g', carbs: '90g', fat: '30g' },
    votes: 67,
  },
  {
    id: '4',
    title: 'Hearty Beef Burger',
    description: 'A juicy, all-beef patty on a toasted brioche bun with all the classic fixings. A timeless comfort food.',
    ingredients: ['150g Ground Beef (80/20)', '1 Brioche Bun', '1 slice Cheddar Cheese', 'Lettuce leaves', 'Tomato slices', 'Red Onion slices', 'Pickle slices', 'Ketchup & Mustard'],
    instructions: '1. Form ground beef into a patty, season with salt and pepper.\n2. Grill or pan-sear the patty for 3-5 minutes per side for medium-rare.\n3. During the last minute of cooking, top with a slice of cheddar cheese to melt.\n4. Lightly toast the brioche bun.\n5. Assemble the burger with your favorite toppings and sauces.',
    imageUrl: 'https://picsum.photos/seed/104/600/400',
    imageHint: 'burger fries',
    dietaryInfo: 'none',
    nutrition: { calories: '850 kcal', protein: '45g', carbs: '55g', fat: '48g' },
    votes: 55,
  },
  {
    id: '5',
    title: 'Tofu & Veggie Stir-fry',
    description: 'A quick, easy, and nutritious stir-fry featuring crispy tofu and a rainbow of fresh vegetables in a savory soy-ginger sauce.',
    ingredients: ['200g Firm Tofu', '1 head of Broccoli, cut into florets', '1 Bell Pepper, sliced', '1 Carrot, julienned', '2 tbsp Soy Sauce', '1 tsp Grated Ginger', '2 cloves Garlic, minced', '1 tsp Sesame Oil'],
    instructions: '1. Press tofu for 30 minutes, then cut into cubes. Pan-fry until golden and crispy.\n2. In a wok or large skillet, heat oil over high heat.\n3. Add broccoli, bell pepper, and carrot. Stir-fry for 3-5 minutes until tender-crisp.\n4. Add ginger and garlic, cook for 1 minute more.\n5. Return tofu to the pan. Add soy sauce and sesame oil, toss to combine, and serve immediately.',
    imageUrl: 'https://picsum.photos/seed/105/600/400',
    imageHint: 'stir-fry',
    dietaryInfo: 'vegan',
    nutrition: { calories: '400 kcal', protein: '25g', carbs: '30g', fat: '20g' },
    votes: 33,
  }
];
