
import { type MenuItem } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  return PlaceHolderImages.find(img => img.id === id)?.imageUrl || `https://picsum.photos/seed/${id}/600/400`;
};

export const initialMenuItems: Omit<MenuItem, "id" | "votes">[] = [
  {
    title: 'Ven Pongal',
    category: 'breakfast',
    day: 'wednesday',
    ingredients: ['Raw Rice', 'Moong Dal', 'Ghee', 'Black Peppercorns', 'Cumin Seeds', 'Cashew Nuts', 'Ginger', 'Curry Leaves'],
    imageUrl: getImage('ven-pongal'),
    imageHint: 'pongal dish',
    dietaryInfo: 'veg',
    submitterId: 'management',
  },
  {
    title: 'Poori Masala',
    category: 'breakfast',
    day: 'thursday',
    ingredients: ['Whole Wheat Flour', 'Potatoes', 'Onions', 'Green Chilies', 'Turmeric Powder', 'Mustard Seeds', 'Urad Dal'],
    imageUrl: getImage('poori-masala'),
    imageHint: 'poori masala',
    dietaryInfo: 'veg',
    submitterId: 'management',
  },
  {
    title: 'Ghee Roast Dosa',
    category: 'breakfast',
    day: 'friday',
    ingredients: ['Dosa Batter', 'Ghee', 'Idli Podi (optional)'],
    imageUrl: getImage('ghee-roast'),
    imageHint: 'ghee roast',
    dietaryInfo: 'veg',
    submitterId: 'management',
  },
  {
    title: 'Bisi Bele Bath',
    category: 'lunch',
    day: 'monday',
    ingredients: ['Rice', 'Toor Dal', 'Mixed Vegetables', 'Bisi Bele Bath Powder', 'Tamarind', 'Ghee', 'Mustard Seeds', 'Peanuts'],
    imageUrl: getImage('bisi-bele-bath'),
    imageHint: 'rice dish',
    dietaryInfo: 'veg',
    submitterId: 'management',
  },
  {
    title: 'Lemon Rice (Chitranna)',
    category: 'lunch',
    day: 'tuesday',
    ingredients: ['Cooked Rice', 'Lemon Juice', 'Mustard Seeds', 'Urad Dal', 'Chana Dal', 'Peanuts', 'Turmeric Powder', 'Green Chilies', 'Curry Leaves'],
    imageUrl: getImage('lemon-rice'),
    imageHint: 'lemon rice',
    dietaryInfo: 'veg',
    submitterId: 'management',
  },
  {
    title: 'Sambar Rice',
    category: 'lunch',
    day: 'thursday',
    ingredients: ['Rice', 'Toor Dal', 'Mixed Vegetables', 'Sambar Powder', 'Tamarind', 'Ghee', 'Mustard Seeds'],
    imageUrl: getImage('sambar-rice'),
    imageHint: 'sambar rice',
    dietaryInfo: 'veg',
    submitterId: 'management',
  },
  {
    title: 'Onion Pakoda',
    category: 'snack',
    day: 'friday',
    ingredients: ['Onions', 'Gram Flour (Besan)', 'Rice Flour', 'Red Chili Powder', 'Asafoetida', 'Curry Leaves', 'Oil for frying'],
    imageUrl: getImage('onion-pakoda'),
    imageHint: 'onion pakoda',
    dietaryInfo: 'veg',
    submitterId: 'management',
  },
  {
    title: 'Masala Vada',
    category: 'snack',
    day: 'tuesday',
    ingredients: ['Chana dal', 'Onion', 'Ginger', 'Garlic', 'Green chilies', 'Fennel seeds', 'Coriander leaves', 'Oil for frying'],
    imageUrl: getImage('masala-vada'),
    imageHint: 'masala vada',
    dietaryInfo: 'veg',
    submitterId: 'management',
  },
  {
    title: 'Egg Puffs',
    category: 'snack',
    day: 'wednesday',
    ingredients: ['Puff Pastry Sheets', 'Boiled Eggs', 'Onion', 'Tomato', 'Ginger-Garlic Paste', 'Spices'],
    imageUrl: 'https://www.yummytummyaarthi.com/wp-content/uploads/2022/09/egg-puffs-1.jpeg',
    imageHint: 'egg puffs',
    dietaryInfo: 'non-veg',
    submitterId: 'management',
  },
  {
    title: 'Chapathi with Kurma',
    category: 'dinner',
    day: 'monday',
    ingredients: ['Whole Wheat Flour', 'Mixed Vegetables', 'Coconut', 'Onion', 'Tomato', 'Ginger-Garlic Paste', 'Spices'],
    imageUrl: getImage('chapathi-kurma'),
    imageHint: 'chapathi kurma',
    dietaryInfo: 'veg',
    submitterId: 'management',
  },
  {
    title: 'Chapathi with Kurma',
    category: 'dinner',
    day: 'wednesday',
    ingredients: ['Whole Wheat Flour', 'Mixed Vegetables', 'Coconut', 'Onion', 'Tomato', 'Ginger-Garlic Paste', 'Spices'],
    imageUrl: getImage('chapathi-kurma'),
    imageHint: 'chapathi kurma',
    dietaryInfo: 'veg',
    submitterId: 'management',
  },
   {
    title: 'Paratha',
    category: 'dinner',
    day: 'saturday',
    ingredients: ['Whole Wheat Flour', 'Ghee', 'Salt', 'Water'],
    imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/paratha-recipe.jpg",
    imageHint: 'paratha bread',
    dietaryInfo: 'veg',
    submitterId: 'management'
  }
];

